---
- name: Configuring Tenant with CSV file
  hosts: apic1
  connection: local
  gather_facts: false
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}' 
      validate_certs: False 
  tasks:

  - name: Get Fault Sumary from APIC
    aci_rest:
      <<: *aci_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: '{{ password }}' 
      path: api/node/class/faultSummary.json
      method: get
    register: query_result

  #- debug: query_result
