---
- name: Start ACI Moitoring
  hosts: apic1
  connection: local
  gather_facts: false
  vars:
    aci_login: &aci_login
      hostname: '{{ inventory_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}' 
      validate_certs: False 
  tasks:

  - name: Get Fault Sumary from APIC
    aci_rest:
      <<: *aci_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: '{{ password }}' 
      path: api/node/class/faultSummary.json
      method: get
    register: query_result

  - name: print result
    debug: 
      var: query_result

  - name: Get Event Sumary from APIC
    aci_rest:
      <<: *aci_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ username }}"
      password: '{{ password }}' 
      path: api/node/mo/topology/HDfabricOverallHealth5min-0.json
      method: get
    register: query_result_event
    
  - name: print result
    debug: 
      var: query_result_event
